version: '3.4'

services:
  public.gateway.reverseproxy:
      build:
        context: .
        dockerfile: gateway/Dockerfile
      container_name: public.gateway.reverseproxy
      environment:
            - SERVERNAME=public.gateway.reverseproxy
      networks:
          - "security-network"
      restart: always
      depends_on: 
        - public.gateway
        - api
      ports:
          - "80:80"
          
  public.gateway:
      image: nginx:alpine
      networks:
          - "security-network"
      container_name: public.gateway
      restart: always
      depends_on: 
        - api
      environment:
            - SERVERNAME=public.gateway.base     

networks:
  security-network:
    driver: bridge